/**
 * Shared styles for the Quiz components
 * Extracted from the main page.jsx for reusability across quiz content types
 */

export const colors = {
    primary: '#22c55e',
    primaryLight: '#86efac',
    primaryDark: '#16a34a',
    lightBg: '#f0fdf4',
    white: '#ffffff',
    dark: '#1e293b',
    gray: '#64748b',
};

export const quizStyles = {
    container: {
        minHeight: '100vh',
        backgroundColor: '#ffffff',
        display: 'flex',
        flexDirection: 'column',
        fontFamily: 'var(--font-nunito), sans-serif',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px 40px',
        borderBottom: `2px solid ${colors.lightBg}`,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        backdropFilter: 'blur(10px)',
        position: 'sticky',
        top: 0,
        zIndex: 10,
    },
    logo: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
    },
    logoIcon: {
        width: '40px',
        height: '40px',
        borderRadius: '12px',
        backgroundColor: colors.primary,
        color: 'white',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
        fontSize: '20px',
        boxShadow: '0 4px 6px -1px rgba(34, 197, 94, 0.2)',
    },
    logoText: {
        fontSize: '22px',
        fontWeight: 700,
        color: colors.dark,
        fontFamily: 'var(--font-fredoka), sans-serif',
    },
    timerContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '8px 16px',
        backgroundColor: colors.lightBg,
        borderRadius: '50px',
        border: `1px solid ${colors.primaryLight}`,
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    },
    timerText: {
        fontSize: '16px',
        fontWeight: 600,
        color: colors.primaryDark,
        fontVariantNumeric: 'tabular-nums',
    },
    mainContent: {
        flex: 1,
        display: 'flex',
        padding: '40px',
        gap: '40px',
        maxWidth: '1200px',
        margin: '0 auto',
        width: '100%',
    },
    sidebar: {
        width: '300px',
        flexShrink: 0,
    },
    sidebarCard: {
        border: `1px solid ${colors.primaryLight}`,
        borderRadius: '24px',
        padding: '24px',
        height: 'fit-content',
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
        backgroundColor: colors.white,
        boxShadow: '0 10px 30px -5px rgba(0, 0, 0, 0.05)',
    },
    sidebarIconPlaceholder: {
        width: '100%',
        height: '160px',
        borderRadius: '16px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.lightBg,
        position: 'relative',
        overflow: 'hidden',
    },
    playButton: {
        width: '48px',
        height: '48px',
        borderRadius: '50%',
        backgroundColor: colors.white,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        boxShadow: '0 4px 12px rgba(34, 197, 94, 0.2)',
        cursor: 'pointer',
        transition: 'transform 0.2s',
    },
    playTriangle: {
        width: 0,
        height: 0,
        borderTop: '8px solid transparent',
        borderBottom: '8px solid transparent',
        borderLeft: `14px solid ${colors.primary}`,
        marginLeft: '4px',
    },
    progressIndicator: {
        marginTop: 'auto',
    },
    progressBar: {
        width: '100%',
        height: '10px',
        backgroundColor: '#f1f5f9',
        borderRadius: '5px',
        overflow: 'hidden',
        marginBottom: '10px',
    },
    progressFill: {
        height: '100%',
        backgroundColor: colors.primary,
        borderRadius: '5px',
        transition: 'width 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
    },
    progressText: {
        fontSize: '14px',
        color: colors.gray,
        textAlign: 'center',
        fontWeight: 500,
    },
    sidebarControls: {
        display: 'flex',
        justifyContent: 'center',
        gap: '12px',
        marginTop: '10px',
    },
    controlCircle: {
        width: '12px',
        height: '12px',
        borderRadius: '50%',
        backgroundColor: colors.primaryLight,
        opacity: 0.5,
    },
    completedCard: {
        maxWidth: '500px',
        margin: '100px auto',
        padding: '50px',
        textAlign: 'center',
        backgroundColor: colors.white,
        borderRadius: '30px',
        border: `1px solid ${colors.primaryLight}`,
        boxShadow: '0 20px 40px -10px rgba(0, 0, 0, 0.1)',
    },
    questionArea: {
        flex: 1,
    },
    completedTitle: {
        fontSize: '32px',
        fontWeight: 700,
        color: colors.dark,
        marginBottom: '12px',
        fontFamily: 'var(--font-fredoka), sans-serif',
    },
    completedText: {
        fontSize: '18px',
        color: colors.gray,
        marginBottom: '32px',
    },
    homeButton: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px 32px',
        backgroundColor: colors.primary,
        color: 'white',
        borderRadius: '50px',
        textDecoration: 'none',
        fontWeight: 700,
        fontSize: '16px',
        boxShadow: '0 4px 15px rgba(34, 197, 94, 0.3)',
        transition: 'transform 0.2s',
    },
};

// Content-specific styles used by quiz content components
export const contentStyles = {
    questionCard: {
        border: `1px solid ${colors.primaryLight}`,
        borderRadius: '24px',
        padding: '40px',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        backgroundColor: colors.white,
        boxShadow: '0 10px 30px -5px rgba(0, 0, 0, 0.05)',
    },
    questionArea: {
        flex: 1,
    },
    questionBox: {
        backgroundColor: colors.lightBg,
        borderRadius: '20px',
        padding: '32px',
        marginBottom: '32px',
        minHeight: '160px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        border: `1px solid ${colors.primaryLight}`,
    },
    questionText: {
        fontSize: '26px',
        fontWeight: 700,
        color: colors.dark,
        marginBottom: '16px',
        fontFamily: 'var(--font-fredoka), sans-serif',
        lineHeight: 1.4,
    },
    questionUnderline: {
        width: '60px',
        height: '4px',
        backgroundColor: colors.primary,
        borderRadius: '2px',
        marginTop: '8px',
    },
    optionsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        marginBottom: '40px',
    },
    optionLabel: {
        display: 'flex',
        alignItems: 'center',
        padding: '18px 24px',
        border: '2px solid',
        borderRadius: '16px',
        cursor: 'pointer',
        transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        gap: '16px',
    },
    customRadio: {
        width: '24px',
        height: '24px',
        borderRadius: '50%',
        border: '2px solid',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'all 0.2s',
        flexShrink: 0,
    },
    optionText: {
        fontSize: '18px',
        color: colors.dark,
        fontWeight: 500,
    },
    navigationButtons: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 'auto',
    },
    navButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '14px 28px',
        border: `2px solid ${colors.primaryLight}`,
        borderRadius: '50px',
        backgroundColor: 'white',
        fontSize: '16px',
        fontWeight: 700,
        color: colors.gray,
        transition: 'all 0.2s',
        cursor: 'pointer',
    },
    nextButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        padding: '16px 32px',
        border: 'none',
        borderRadius: '50px',
        backgroundColor: colors.primary,
        fontSize: '16px',
        fontWeight: 700,
        color: 'white',
        cursor: 'pointer',
        transition: 'all 0.2s',
        boxShadow: '0 4px 15px rgba(34, 197, 94, 0.3)',
    },
    // Audio-specific styles
    audioContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '20px',
        padding: '24px',
        backgroundColor: colors.lightBg,
        borderRadius: '16px',
        marginBottom: '24px',
    },
    audioPlayer: {
        width: '100%',
        maxWidth: '400px',
    },
    // Visual-specific styles
    imageContainer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '24px',
        backgroundColor: colors.lightBg,
        borderRadius: '16px',
        marginBottom: '24px',
        minHeight: '200px',
    },
    questionImage: {
        maxWidth: '100%',
        maxHeight: '300px',
        borderRadius: '12px',
        objectFit: 'contain',
    },
    visualOptionsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '16px',
        marginBottom: '40px',
    },
    visualOption: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '16px',
        border: '2px solid',
        borderRadius: '16px',
        cursor: 'pointer',
        transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        gap: '12px',
    },
    visualOptionImage: {
        width: '100%',
        height: '120px',
        objectFit: 'contain',
        borderRadius: '8px',
    },
    // Minigame-specific styles
    minigameContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '24px',
        padding: '32px',
        backgroundColor: colors.lightBg,
        borderRadius: '20px',
        marginBottom: '24px',
        minHeight: '300px',
    },
    minigameInstruction: {
        fontSize: '16px',
        color: colors.gray,
        textAlign: 'center',
    },
};
